case $- in
    *i*) ;;
      *) return;;
esac

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

shopt -s histappend
shopt -s checkwinsize

if [ -z "${alpine_chroot:-}" ] && [ -r /etc/alpine_chroot ]; then
    alpine_chroot=$(cat /etc/alpine_chroot)
fi

PS1='${alpine_chroot:+($alpine_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
